### ISSUE TITLE
Build error on ios

### ISSUE THREAD

**Issue by joe-pritchard** [stewwan/capacitor-twitter#1]
After adding the plugin, I receive the error ":-1: Undefined symbol: _OBJC_CLASS_$_TWTRTwitter" in xcode... I've followed the steps in the readme, but is there something extra needed for ios?

**Comment by rlaurente** [comment]
I got it too, any updates on this error ?

**Comment by rlaurente** [comment]
Quick fix for this issue is downgrading pod to 1.5.3. 
Thanks

**Comment by stewwan** [comment]
Thanks 🙏 @rlaurente
