### ISSUE TITLE
Problem in Android - Javascript is not available

### ISSUE THREAD

**Issue by BryanCastroMCM** [stewwan/capacitor-twitter#17]
When the user enters his twitter account credentials and performs the authentication on android (This only fails on ANDROID), it returns a screen with the title "Javascript is not available". 
I checked and all WebViews have javascript enabled. 
I tested with 3 devices:
- Poco F3
- Pixel 3 Emulator
- Xiaomi Mi A2 Lite

**Screenshots**
![Screenshot_1671641923](https://user-images.githubusercontent.com/116398926/208962872-0682fbc9-63ce-4fbb-800f-690762a7bfc8.png)

https://user-images.githubusercontent.com/116398926/208962892-addf6f24-d25d-4209-88a7-8155c5bb5502.mp4

 - Version @capacitor-community/twitter - 3.0.2

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android 12

**Comment by AnkitMaheshwariIn** [comment]
Any solution to this problem?

**Comment by BryanCastroMCM** [comment]
No, I removed auth with twitter.

**Comment by AnkitMaheshwariIn** [comment]
Ok, thanks

**Comment by BryanCastroMCM** [comment]
⚠ Plugin Deprecated - CLOSE ISSUE ⚠

**Comment by AnkitMaheshwariIn** [comment]
Any alternative to this plugin for Twitter in Android?

**Comment by stewones** [comment]
> 

none. Twitter deprecated it a few years ago and now removed. I should archive this project.

you need to implement OAuth2
